  # Profile PROD: dùng MySQL thật.
spring:
  datasource:
    url: jdbc:mysql://ns95.dailysieure.com:3306/tinhtriprocom_tinhtriprocom?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tinhtriprocom_tinhtriprocom
    password: Az9Daily72053354

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
